# idea_generator.py
#
# Functionality：
#   1. Based on research_gaps generated by gap_miner
#   2. Generates several specific research ideas for each gap
#   3. Each idea is structured: title, question, innovation, methodology summary, dataset, baseline, metrics, etc.
#
# This is the direct input for the subsequent idea evaluator and paper draft generator.

import json
from typing import Dict, Any, List

from llm_client import call_llm_raw
from gap_miner import mine_research_gaps


SYSTEM_PROMPT_IDEA_GENERATOR = """You are an expert ML researcher and paper writer.
Given a set of research gaps, you propose concrete, publication-level research ideas.

Each idea should be specific enough that it could plausibly become a full conference paper
(e.g., NeurIPS/ICML/ACL/CVPR workshop/main track), not just a vague direction.
You MUST output strict JSON only.
"""


def build_idea_generation_prompt(gaps_result: Dict[str, Any]) -> str:
    """
    Construct a prompt, pass research_gaps to the model, and ask it to generate several ideas for each gap.
    """
    gaps_json = json.dumps(gaps_result, indent=2, ensure_ascii=False)

    prompt = f"""
You are given a JSON object 'gaps_result' that has the following structure:

{{
  "research_gaps": [
    {{
      "gap_id": "G1",
      "description": "...",
      "why_important": "...",
      "related_papers": [
        {{
          "paper_index": 0,
          "title": "...",
          "evidence_from_paper": "..."
        }}
      ],
      "suggested_directions": [
        "direction 1",
        "direction 2"
      ]
    }},
    ...
  ]
}}

Here is the actual JSON (DO NOT repeat it in your output):
{gaps_json}

Based on these research gaps, generate a set of concrete research ideas.

Output a STRICT JSON object with the following structure:

{{
  "ideas": [
    {{
      "idea_id": "I1",
      "gap_id": "G1",
      "working_title": "A plausible paper-style title",
      "problem_statement": "2-4 sentences describing the specific research problem.",
      "hypothesis": "1-3 sentences describing the main hypothesis.",
      "novelty": "2-4 sentences explaining what is novel compared to existing work.",
      "method_outline": "4-8 sentences outlining the key technical components of the proposed method.",
      "datasets": [
        "Suggested dataset 1",
        "Suggested dataset 2"
      ],
      "baselines": [
        "Baseline method 1",
        "Baseline method 2"
      ],
      "metrics": [
        "Metric 1",
        "Metric 2"
      ],
      "risk_factors": [
        "Potential risk or difficulty 1",
        "Potential risk or difficulty 2"
      ]
    }},
    ...
  ]
}}

Rules:
- For each research gap, generate 1-3 ideas (you can decide based on how rich the gap is).
- You MUST reference the corresponding "gap_id" correctly in each idea.
- Ideas should be as concrete and technically detailed as possible, but you may assume a typical ML setting.
- Use well-known datasets/baselines/metrics where possible, consistent with the topic.
- Output VALID JSON only, with double quotes, no comments, no markdown fences.
"""
    return prompt


def generate_ideas_from_gaps(gaps_result: Dict[str, Any]) -> Dict[str, Any]:
    """
    Call LLM to generate ideas JSON based on research_gaps.
    """
    user_prompt = build_idea_generation_prompt(gaps_result)
    raw_output = call_llm_raw(
        system_prompt=SYSTEM_PROMPT_IDEA_GENERATOR,
        user_prompt=user_prompt,
        max_output_tokens=3000,
    )

    try:
        result = json.loads(raw_output)
    except json.JSONDecodeError:
        print("Failed to parse JSON from idea generator.")
        print("Raw output:\n", raw_output)
        raise

    return result


def pretty_print_ideas(ideas_result: Dict[str, Any]):
    """
    Print the idea list
    """
    ideas: List[Dict[str, Any]] = ideas_result.get("ideas", [])
    print("\n=== Generated Research Ideas ===")
    if not ideas:
        print("No ideas found or JSON structure unexpected.")
        return

    for idea in ideas:
        idea_id = idea.get("idea_id", "Unknown")
        gap_id = idea.get("gap_id", "Unknown")
        title = idea.get("working_title", "")
        problem_statement = idea.get("problem_statement", "")
        hypothesis = idea.get("hypothesis", "")
        novelty = idea.get("novelty", "")
        method_outline = idea.get("method_outline", "")
        datasets = idea.get("datasets", [])
        baselines = idea.get("baselines", [])
        metrics = idea.get("metrics", [])
        risk_factors = idea.get("risk_factors", [])

        print(f"\n[{idea_id}] (gap_id={gap_id})")
        print(f"Title:")
        print(f"  {title}")

        print("\nProblem statement:")
        print(f"  {problem_statement}")

        print("\nHypothesis:")
        print(f"  {hypothesis}")

        print("\nNovelty:")
        print(f"  {novelty}")

        print("\nMethod outline:")
        print(f"  {method_outline}")

        print("\nDatasets:")
        for d in datasets:
            print(f"  - {d}")

        print("\nBaselines:")
        for b in baselines:
            print(f"  - {b}")

        print("\nMetrics:")
        for m in metrics:
            print(f"  - {m}")

        print("\nRisk factors:")
        for r in risk_factors:
            print(f"  - {r}")

        print("-" * 80)

    print("\n================================\n")


def main():
    print("=== Research Idea Generator Demo ===")
    topic = input("Enter a topic (e.g., 'large language models'): ").strip()
    if not topic:
        topic = "large language models"

    # Step 1: do gap mining
    print("\n[1] Mining research gaps first ...")
    gaps_result = mine_research_gaps(topic, max_papers=3)

    # Step 2: generate ideas based on research gaps
    print("\n[2] Generating concrete research ideas based on gaps ...")
    ideas_result = generate_ideas_from_gaps(gaps_result)

    # Step 3: print ideas
    pretty_print_ideas(ideas_result)


if __name__ == "__main__":
    main()
